import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'SVT',
  description: 'Generated by ankit kherwa',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="ff-k2d">{children}</body>
    </html>
  )
}
